-- api/schema.sql
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS telemetry (
  id INT PRIMARY KEY AUTO_INCREMENT,
  robotId VARCHAR(100),
  payload JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS commands (
  id INT PRIMARY KEY AUTO_INCREMENT,
  robotId VARCHAR(100),
  command JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
